-- Active: 1718361914524@@127.0.0.1@3306@uni_karamoozi
CREATE Table stu_request(
    id INT PRIMARY KEY AUTO_INCREMENT,
    code VARCHAR(255) UNIQUE NOT NULL,
    user_id INT NOT NULL,
    semester_id INT NOT NULL,
    group_id INT NOT NULL,
    stu_semester_id INT NOT NULL,
    teacher INT NOT NULL,
    type INT NOT NULL,
    ira_id INT NULL,
    intern_name VARCHAR(255) NOT NULL,
    intern_phone VARCHAR(255) NOT NULL,
    intern_telephone VARCHAR(255) NOT NULL,
    from_date DATE NOT NULL,
    to_date DATE NOT NULL,
    place_name VARCHAR(255) NULL,
    place_telephone VARCHAR(255) NULL,
    supervisor_name VARCHAR(255) NULL,
    supervisor_phone VARCHAR(255) NULL,
    sat BOOLEAN NULL,
    sat_from TIME NULL,
    sat_to TIME NULL,
    sun BOOLEAN NULL,
    sun_from TIME NULL,
    sun_to TIME NULL,
    mon BOOLEAN NULL,
    mon_from TIME NULL,
    mon_to TIME NULL,
    tue BOOLEAN NULL,
    tue_from TIME NULL,
    tue_to TIME NULL,
    wed BOOLEAN NULL,
    wed_from TIME NULL,
    wed_to TIME NULL,
    thu BOOLEAN NULL,
    thu_from TIME NULL,
    thu_to TIME NULL,
    description TEXT NULL,
    teacher_confirm BOOLEAN NULL,
    teacher_description TEXT NULL,
    manager_confirm BOOLEAN NULL,
    manager_description TEXT NULL,
    status BOOLEAN DEFAULT 1 NULL,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL,
    created_by int NULL,
    updated_by int NULL,
    Foreign Key (user_id) REFERENCES users(id),
    Foreign Key (semester_id) REFERENCES semester(id),
    Foreign Key (group_id) REFERENCES uni_group(id),
    Foreign Key (stu_semester_id) REFERENCES stu_semesters(id),
    Foreign Key (teacher) REFERENCES users(id),
    Foreign Key (ira_id) REFERENCES intern_recruitment_application(id)
)